"""empty message

Revision ID: 20bcb3e6d7e5
Revises: 
Create Date: 2017-12-15 18:16:07.587976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bcb3e6d7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('documentsPhotoId', sa.Integer(), nullable=True))
    op.add_column('manager', sa.Column('personalInformationId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manager', 'documentsPhoto', ['documentsPhotoId'], ['id'])
    op.create_foreign_key(None, 'manager', 'personalInformation', ['personalInformationId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_constraint(None, 'manager', type_='foreignkey')
    op.drop_column('manager', 'personalInformationId')
    op.drop_column('manager', 'documentsPhotoId')
    # ### end Alembic commands ###
